# Pushes the contents of the repo to the Codeberg mirror
name: ðŸªž Mirror - Sync with Codeberg repo
on:
  schedule: [{ cron: '45 01 * * 0' }]
  push: { tags: ['v*'] }
  workflow_dispatch:

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - uses: lissy93/repo-mirror-action@main
        with:
          ssh_key: ${{ secrets.MIRROR_SSH }}
          host: git@codeberg.org
          user: alicia
          repo: email-comparison
